#!/bin/bash
version="11.3.0"
wget https://dl.grafana.com/oss/release/grafana-${version}.linux-amd64.tar.gz
tar -xvzf grafana-${version}.linux-amd64.tar.gz -C /usr/share/
mv /usr/share/grafana-v${version} /usr/share/grafana

servicefile=$(cat <<'EOF'
[Unit]
Description=Grafana instance

[Service]
ExecStart=/usr/share/grafana/bin/grafana-server -homepath /usr/share/grafana web

[Install]
WantedBy=default.target
EOF
)

echo "$servicefile" > /etc/systemd/system/grafana-server.service
systemctl daemon-reload
systemctl enable --now grafana-server.service
systemctl status grafana-server.service
rm -rf grafana*
