#!/bin/bash
version="2.55.0"
wget https://github.com/prometheus/prometheus/releases/download/v${version}/prometheus-${version}.linux-amd64.tar.gz
tar -xvzf prometheus-${version}.linux-amd64.tar.gz -C /etc/
mv /etc/prometheus-${version}.linux-amd64 /etc/prometheus
cp /etc/prometheus/{prometheus,promtool} /usr/bin/
rm -rf /etc/prometheus/{prometheus,promtool}
mkdir /var/lib/prometheus
servicefile=$(cat <<'EOF'
[Unit]
Description=Prometheus

[Service]
User=root
ExecStart=/usr/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path /var/lib/prometheus/ --web.console.templates=/etc/prometheus/consoles --web.console.libraries=/etc/prometheus/console_libraries --web.external-url=http://0.0.0.0:9090/

[Install]
WantedBy=default.target
EOF
)
echo "$servicefile" > /etc/systemd/system/prometheus-server.service
systemctl daemon-reload
systemctl enable --now prometheus-server.service
systemctl status prometheus-server.service
rm -rf prom*
