#!/bin/bash
version="1.8.2"
wget https://github.com/prometheus/node_exporter/releases/download/v${version}/node_exporter-${version}.linux-amd64.tar.gz
tar -xvzf node_exporter-${version}.linux-amd64.tar.gz -C /opt/
cp /opt/node_exporter-${version}.linux-amd64/node_exporter /usr/bin/
servicefile=$(cat <<'EOF'
[Unit]
Description=Node Exporter

[Service]
User=root
ExecStart=/usr/bin/node_exporter 

[Install]
WantedBy=default.target
EOF
)

echo "$servicefile" > /etc/systemd/system/node_exporter.service
systemctl daemon-reload
systemctl enable --now node_exporter.service
systemctl status node_exporter.service
rm -rf node* 
rm -rf /opt/node*
